require File.expand_path('../remove_ios_only_frameworks', __FILE__)

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Sample' do
  pod 'AppCenter/Analytics'
  pod 'Firebase/Analytics'
end

#Configure your macCatalyst dependencies
# catalyst_configuration do
# 	# Uncomment the next line for a verbose output
# 	# verbose!
#
# 	ios 'Firebase/Analytics' # This dependency will only be available only for iOS
# 	macos 'AppCenter/Analytics' # This dependency will only be available only for macOS
# end

def catalyst_unsupported_pods
  ['Firebase/Analytics']
end

#Configure your macCatalyst App
post_install do |installer|
	installer.configure_support_catalyst
end
